### ISSUE TITLE
Application distribution

### ISSUE THREAD

**Issue by blue0513** [blue0513/slackdeck-proto#33]
Build the electron app and distribute it!  
cf: [Application Distribution](https://electronjs.org/docs/tutorial/application-distribution)

**Comment by munierujp** [comment]
If you distribute as an application, it would be awesome to have a landing page.

like these:

* [Clipy - Clipboard extension app for macOS](https://clipy-app.com/)
* [エディ太郎 - 下書き専用テキストエディタ](https://editaro.com/)

**Comment by blue0513** [comment]
[v0.10.0](https://github.com/blue0513/slackdeck-proto/releases/tag/0.10.0) released 🎉 (Only for MacOS)

**Comment by blue0513** [comment]
Since partially realized, I'll close this issue 🤝  
@munierujp Thx for the suggestion 👍
