### ISSUE TITLE
Show channel name on each column

### ISSUE THREAD

**Issue by munierujp** [blue0513/slackdeck-proto#37]
I'd like to see channel name on each column.

## My idea
I think that there is two way for showing channel name.

### Show original header

![スクリーンショット 2019-06-27 12 36 43](https://user-images.githubusercontent.com/20086673/60232687-476a0880-98d8-11e9-9eb2-4844754137cc.png)

### Show channel name in tool bar
![スクリーンショット 2019-06-27 12 40 27](https://user-images.githubusercontent.com/20086673/60232845-cd864f00-98d8-11e9-9ce9-21a87aeffabe.png)

DOM:

```html
<div class="tab-tool-bar">
  <header>
    <span class="channel-name">#general</span>
  </header>
  <nav>
    <button onclick="reload(0);">Reload</button>
    <button onclick="remove(0);">Remove Column</button>
    <button onclick="add();">Add Column</button>
  </nav>
</div>
```

**Comment by munierujp** [comment]
Sorry, duplicate with #18

**Comment by blue0513** [comment]
@munierujp Thx! I think `Show channel name in tool bar` is better way. I'll try it soon.
