### ISSUE TITLE
WebView security consideration

### ISSUE THREAD

**Issue by saiya** [blue0513/slackdeck-proto#54]
Security in Electron is complicated topic. I think it is worth to check it out to make safe application. 

Summarized document (in 2017 BlackHat): https://www.blackhat.com/docs/us-17/thursday/us-17-Carettoni-Electronegativity-A-Study-Of-Electron-Security-wp.pdf

Especially, current slackdeck-proto implementation simply uses `webview` element. Is it enough secure?

Since I am not professional in Electron world, I don't have comprising knowledge. What I can suggest is to look what Slack official app doing.

**Comment by saiya** [comment]
Also I made a PR to fix `openExternal` issue: https://github.com/blue0513/slackdeck-proto/pull/53

**Comment by blue0513** [comment]
As for slackdeck-proto, it cannot open the non http(s) URL (Probably, I guess, Slack itself is controlling this kind of action). 

However, as you said, we should make it much more safe application and slackdeck-proto itself should prevent opening non http(s) URL.

Thank you for the PR. I'll check it then merge 👍

**Comment by blue0513** [comment]
@saiya Merged! Thx 👍
